# Generated by Django 3.0.7 on 2020-07-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name_plural': 'Artists'},
        ),
    ]
