# Generated by Django 3.0.7 on 2020-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20200708_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artists',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
