# Generated by Django 3.0.7 on 2020-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(default='name', max_length=254),
            preserve_default=False,
        ),
    ]
